version: '3.7'
services:
  nginx:
    image: nginx:1.17.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  tratschtante-client:
    image: 778593510599.dkr.ecr.eu-west-2.amazonaws.com/tratschtante-client
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    command: yarn watch
    volumes:
      - ../frontend/:/app
    working_dir: /app
  tratschtante-api:
    image: 778593510599.dkr.ecr.eu-west-2.amazonaws.com/tratschtante-api
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: yarn watch
    volumes:
      - ../api:/app
    working_dir: /app
